//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriIletisim.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusteriBilgileriDbEntities : DbContext
    {
        public MusteriBilgileriDbEntities()
            : base("name=MusteriBilgileriDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Iletisim> Iletisims { get; set; }
        public virtual DbSet<IlgiAlanlari> IlgiAlanlaris { get; set; }
        public virtual DbSet<ilceler> ilcelers { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<Kisi> Kisis { get; set; }
        public virtual DbSet<KisiIlgi> KisiIlgis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
