//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriIletisim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iletisim()
        {
            this.Kisis = new HashSet<Kisi>();
        }
    
        public int IletisimID { get; set; }
        public string E_mail { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public int SehirID { get; set; }
        public int IlceID { get; set; }
    
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kisi> Kisis { get; set; }
    }
}
