//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusteriIletisim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlgiAlanlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlgiAlanlari()
        {
            this.IlgiAlanlari1 = new HashSet<IlgiAlanlari>();
            this.KisiIlgis = new HashSet<KisiIlgi>();
        }
    
        public int IlgiAlaniID { get; set; }
        public string IlgiAlaniAdi { get; set; }
        public Nullable<int> UstKategori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlgiAlanlari> IlgiAlanlari1 { get; set; }
        public virtual IlgiAlanlari IlgiAlanlari2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KisiIlgi> KisiIlgis { get; set; }
    }
}
